### PR TITLE
Add new GCS system in the readme.md for the IOS ecosystem

### PR DESCRIPTION
**Pull request by wx4cb**
Sidepilot [https://sidepilot.net/](url) is an alternative GCS/TElemetry viewer for the IOS Ecosystem. tested well on a 2021 ipad 12.9" with the latest iPadOS and the latest INAV Version (4.0-RC1). Just allows for viewing the telemetry (tested via a wifi connection to a crossfire module)

### CODE REVIEW

**Comment by stronnag** [comment]
Please create your*own* branch off development.

**Comment by wx4cb** [comment]
i know, thats why i closed it.. I did it on the wrong one..

**Comment by stronnag** [comment]
And I'm not sure mwp is the right place to document Ardupilot tools.

**Comment by wx4cb** [comment]
i was juts adding to the list of tools you had in the main readme that work with inav. (like you have with QGC etc :D)

**Comment by stronnag** [comment]
Yes, you're correct; you could use the very nice looking app to create missions and convert them with `impload`. Accepted.

**Comment by wx4cb** [comment]
havent gotten that far with it, just found out about it, but yes. it does work very well for at least viewing the telemetry :D

**Pull request closed without merging**
